### ISSUE TITLE
Use `cpus` reserved name in `job.resources.scalar`

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed#100] opened 2018-04-06 13:54 UTC
Usage within Mesos / Marathon is consistently `cpus` and we should be consistent with that. We need to change all references to `cpu` to `cpus` within the spec.

**Comment by gisjedi** [comment] 2018-04-06 13:55
@JohnPTobe we need to make sure we propogate this change into seed-common / seed-cli. Can we verify what impact this has and if changes are needed create appropriate linked issues?

**Comment by JohnPTobe** [comment] 2018-04-06 14:07
just did a search on the code base and it should be just updating the tests and the example images

**Comment by JohnPTobe** [comment] 2018-04-06 14:10
is this a dupe of #99?

**Closed as completed** 2018-04-20 12:46 UTC
Labels: breaking change
